[package]
name = "jsonnet-ls"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "jsonnet-ls"
test = false

[lints]
workspace = true

[dependencies]
