[package]
name = "jsonnet-expr"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
test = false
doctest = false

[dependencies]
la-arena.workspace = true
rustc-hash.workspace = true

[build-dependencies]
quote.workspace = true
identifier-case.workspace = true
write-rs-tokens.workspace = true
