[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
# third party
drop_bomb = "0.1.5"
la-arena = "0.3.1"
prettyplease = "0.2.15"
quote = "1.0.33"
rowan = "0.15.13"
rustc-hash = "1.1.0"
syn = "2.0.38"
text-size = "1.1.1"

# language util
code-h2-md-map.git = "https://github.com/azdavis/language-util.git"
syntax-gen.git = "https://github.com/azdavis/language-util.git"
token.git = "https://github.com/azdavis/language-util.git"
event-parse.git = "https://github.com/azdavis/language-util.git"
