[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
# third party
drop_bomb = "0.1.5"
la-arena = "0.3.1"
rowan = "0.15.11"
rustc-hash = "1.1.0"

# language util
syntax-gen.git = "https://github.com/azdavis/language-util.git"
token.git = "https://github.com/azdavis/language-util.git"
