[package]
name = "jsonnet-desugar"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
jsonnet-syntax.path = "../jsonnet-syntax"
jsonnet-hir.path = "../jsonnet-hir"
