[package]
name = "jsonnet-desugar"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
text-size.workspace = true

jsonnet-expr.path = "../jsonnet-expr"
jsonnet-prim.path = "../jsonnet-prim"
jsonnet-syntax.path = "../jsonnet-syntax"
