[package]
name = "jsonnet-pointers"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
rustc-hash.workspace = true

jsonnet-expr.path = "../jsonnet-expr"
jsonnet-syntax.path = "../jsonnet-syntax"
