[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "xtask"
test = false

[lints]
workspace = true

[dependencies]
flate2.workspace = true
pico-args.workspace = true
