[package]
name = "jsonnet-prim"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
rustc-hash.workspace = true

[build-dependencies]
quote = "1.0.33"
prettyplease = "0.2.15"
syn = "2.0.38"
