[package]
name = "jsonnet-lex"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
drop_bomb.workspace = true
token.workspace = true

jsonnet-syntax.path = "../jsonnet-syntax"
