[package]
name = "jsonnet-statics"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
test = false
doctest = false

[dependencies]
paths.workspace = true
rustc-hash.workspace = true

always.path = "../always"
jsonnet-expr.path = "../jsonnet-expr"
