[package]
name = "topo-sort"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[lints]
workspace = true

[dependencies]
always.workspace = true
rustc-hash.workspace = true
