[package]
name = "jsonnet-token"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
test = true
doctest = false

[dependencies]
indoc.workspace = true

[dev-dependencies]
rustc-hash.workspace = true
