[package]
name = "jsonnet-eval"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
test = false
doctest = false

[dependencies]
rustc-hash.workspace = true
paths.workspace = true

jsonnet-expr.path = "../jsonnet-expr"
