[package]
name = "jsonnet-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
jsonnet-lex.path = "../jsonnet-lex"
jsonnet-parse.path = "../jsonnet-parse"
